# Generated by Django 2.2 on 2021-03-20 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_auto_20210311_1914'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicerecord',
            old_name='desc',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='servicerecord',
            old_name='private_notes',
            new_name='notes',
        ),
        migrations.RenameField(
            model_name='servicerecord',
            old_name='date_performed',
            new_name='service_date',
        ),
        migrations.AddField(
            model_name='servicerecord',
            name='receipt',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
