# Generated by Django 2.2 on 2021-03-21 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0005_auto_20210320_2337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerecord',
            name='notes',
        ),
        migrations.AddField(
            model_name='servicerecord',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='servicerecord',
            name='work_type',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='servicerecord',
            name='service_receipt',
            field=models.ImageField(blank=True, help_text='Keep a copy of your receipt here', null=True, upload_to='images/'),
        ),
    ]
