# Generated by Django 2.2 on 2021-03-23 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0006_auto_20210321_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='engine',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='style',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='trim',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='vin',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='servicerecord',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='servicerecord',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='servicerecord',
            name='service_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicerecord',
            name='service_receipt',
            field=models.ImageField(blank=True, help_text='Keep a copy of your receipt here', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='servicerecord',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='servicerecord',
            name='work_type',
            field=models.CharField(max_length=50),
        ),
    ]
