# Generated by Django 2.2 on 2021-03-23 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0007_auto_20210323_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='engine',
            field=models.CharField(blank=True, default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='odometer',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='car',
            name='style',
            field=models.CharField(blank=True, default='N/A', max_length=255),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(blank=True, default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='trim',
            field=models.CharField(blank=True, default='N/A', max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='vin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='servicerecord',
            name='odometer',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
