# Generated by Django 2.2 on 2021-03-23 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0009_auto_20210323_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='style',
        ),
    ]
