# Generated by Django 2.2 on 2021-03-23 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0010_remove_car_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerecord',
            name='service_receipt',
            field=models.ImageField(blank=True, default='invoice_receipt.jpeg', help_text='Keep a copy of your receipt here', upload_to='images/'),
        ),
    ]
