# Generated by Django 2.2 on 2021-04-27 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0011_auto_20210323_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerecord',
            name='service_receipt',
            field=models.ImageField(blank=True, default='invoice_receipt.png', help_text='Keep a copy of your receipt here', upload_to='images/'),
        ),
    ]
