# Generated by Django 2.2 on 2021-05-02 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0013_auto_20210502_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.PositiveIntegerField(),
        ),
    ]
