# Generated by Django 2.2 on 2021-05-02 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0014_auto_20210502_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerecord',
            name='odometer',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
